### PR TITLE
Fix Quaternion Logarithm

### PR DESCRIPTION
**Pull request by wyager**
The previous quaternion logarithm algorithm wasn't quite correct. I don't fully understand the reasoning behind some of the edge cases handled by the quaternion code, so I can only speak for the standard case, which now matches Wikipedia's definition and seems to work correctly.

### CODE REVIEW

**Comment by wyager** [comment]
Resolves #126

**Comment by ekmett** [comment]
Trying to figure out if the pi in that code was originally an 'i' that got typoed.

**Comment by wyager** [comment]
It looks like you explicitly underscored the original 'i'. I could see pi being correct for some obscure floating point math reason.

**Comment by ekmett** [comment]
A lot of this quaternion code was transcoded in bulk from an old C++ codebase I had written a couple of decades prior. Unfortunately, I don't have easy access to that code any more. (It is on an old hard-drive somewhere in a pile of old hard-drives.)

**Comment by ekmett** [comment]
I finally had a chance to take a look at this properly. 

Then `atan2` was probably me trying to be clever.

The preservation of `v` before was deliberate. When `qiq` was 0, `v` consists entirely of 0 and -0 coefficients.

On the other hand, the `pi` was a nonsense typo introduced by the translation from the original code. That said, we should do something more sensible for the cases where you have a negative scalar and zero imaginary components for totality's sake. Pointwise negation of a quaternion represents the same rotation, so to take the 'log' of a negative scalar number, we first, negate the quaternion pointwise, take the log, then to avoid having to multiply each coefficient of v by -1, and to preserve the double cover, I negate again. The result is that you then should be able to use`v` vector unmolested (recall it just consists of positive and negative zeroes) just as in the positive case.

**Pull request merged**
