### PR TITLE
Fix segfault in basicUnsafeWrite implementation for MVector (V n a)

### PR DESCRIPTION
**Pull request by ian-mi**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
There's astonishingly little context here for us to gauge what this PR is accomplishing. Can you give us an example of how you can use `basicUnsafeWrite` for `V n a` to cause a segfault? And can you identify what the problem is, and what your PR does to solve the issue?

**Comment by ian-mi** [comment]
Almost any use of the current version of this function results in a segfault. For example:
```
*Linear> import Data.Vector.Unboxed
*Linear Data.Vector.Unboxed> import Linear.V
*Linear Data.Vector.Unboxed Linear.V> :set -XDataKinds
*Linear Data.Vector.Unboxed Linear.V> :set -XScopedTypeVariables
*Linear Data.Vector.Unboxed Linear.V> let (v :: V 10 Int) = pure 5
*Linear Data.Vector.Unboxed Linear.V> v
V {toVector = [5,5,5,5,5,5,5,5,5,5]}
*Linear Data.Vector.Unboxed Linear.V> fromList [v]
Segmentation fault
```

There are several ways in which the existing code is not correct making me believe that variable names got confused at some point. For example, the existing code attempts to read from vn using the index `i` when `i` should be the index to write into `v`. Additionally for an unknown reason `i` is decremented at the end of go causing elements to be written in the wrong order (which also triggers a read at index -1 causing the segfault we see in this example).

To fix this I have replaced the use of the index `i` with a new index `j` into `vn` which ranges from `0` to `d - 1`. Looking through the commit history this is indeed similar to how the old version of this function worked using `imapM_`: https://github.com/ekmett/linear/commit/b735fd17

This code could be simplified by removing several arguments to `go` and moving `d` back into a where clause but I suspected that it was written in this way for performance reasons so I left it as is.

**Comment by ekmett** [comment]
This goes to show you how much the vector instance there has been torture tested. =)

**Comment by RyanGlScott** [comment]
Right. Perhaps we should add a unit test for this?

**Comment by RyanGlScott** [comment]
Done in #125.

**Comment by ian-mi** [comment]
Thank you for getting this merged so quickly. I'm surprised that I am the only one using these instances, I've found them to be a useful way to work around the memory overhead of working with many boxed vectors. Any plans for a new point release?

**Comment by RyanGlScott** [comment]
I think we'll work on releasing a bunch of package updates to Hackage when GHC 8.2-rc1 is released (which should be Real Soon Now).

**Pull request merged**
