### PR TITLE
Tighten lower bound on lens, since the bigger FieldN classes are used

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by gwils** [comment]
As a hackage trustee, I've made metadata revisions to linear-1.20.{6,7} to tighten their lower bound on lens to `>=4.13`, since there is a name clash with `Control.Lens.coerce` that causes compilation failure on lower lens versions.

**Comment by RyanGlScott** [comment]
I'm a bit confused. Do the lower bounds now need to be revised further to reflect this PR?

**Comment by gwils** [comment]
Sorry, I could have been clearer.

The changes that required `lens >= 4.13` affected 1.20.{6,7}
Recently more changes were introduced that require `lens >= 4.15.2`, but those changes haven't made it into a hackage release yet.

So all the bounds should be fine now.

**Comment by RyanGlScott** [comment]
Got it, thanks.

**Pull request merged**
